### ISSUE TITLE
Error after adding payment pointer

### ISSUE THREAD

**Issue by mudrd8mz** [andrewhancox/moodle-local_webmonetization#2]
I followed the description and added a payment pointer to a course category. I received the following error and I can't use the site since then:

Exception - Return value of local_webmonetization\receiptverifier::get_receiptverifier() must be an instance of local_webmonetization\receiptverifier or null, none returned
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 102 of /local/webmonetization/classes/receiptverifier.php: TypeError thrown
    line 55 of /local/webmonetization/lib.php: call to local_webmonetization\receiptverifier::get_receiptverifier()
    line 657 of /lib/outputrenderers.php: call to local_webmonetization_before_standard_html_head()
    line 219 of /lib/mustache/src/Mustache/Context.php: call to core_renderer->standard_head_html()
    line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
    line 31 of data/localcache/mustache/1639513276/boost/__Mustache_5d2c5b634f028cc9d1e1a83931c95cb2.php: call to Mustache_Context->findDot()
    line 13 of data/localcache/mustache/1639513276/boost/__Mustache_b67fa074c2fe667346f4a01dcb799898.php: call to __Mustache_5d2c5b634f028cc9d1e1a83931c95cb2->renderInternal()
    line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_b67fa074c2fe667346f4a01dcb799898->renderInternal()
    line 200 of /lib/outputrenderers.php: call to Mustache_Template->render()
    line 59 of /theme/boost/layout/columns2.php: call to renderer_base->render_from_template()
    line 1400 of /lib/outputrenderers.php: call to include()
    line 1330 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 86 of /local/webmonetization/editcontextpaymentpointer.php: call to core_renderer->header()

**Comment by andrewhancox** [comment]
Bug in default setting, sorted - thanks for the report!
